Items:
  regalo_proximo:
    id: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmNhYWQ4NmM3MDhlYjI3NzczYTY0ZjkzNDc5ZTM5ZjA0NDJhNWNlMDg2YjYzMjk2YzdiN2QxY2Y1MTE2MDk1NiJ9fX0=
    name: "&fRegalo dia &a%day%"
    lore:
      - "&7Estado: &6&lBLOQUEADO"
      - ""
      - "&7¡Podras reclamar este regalo el"
      - "&a%day% &7de diciembre!"
  regalo_ya_reclamado:
    id: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWRkODY3M2Y4NDJlNTBmMTMxYjM3N2M4NGI2ZmU1MWMyMTkxMDZkZjNmYmMwOTFhN2JjOTI2OWI5MWM2NjA1MiJ9fX0=
    name: "&fRegalo dia &a%day%"
    lore:
      - "&7Estado: &b&lRECLAMADO"
      - ""
      - "&7¡Ya has reclamado esa recompensa!"
  regalo_disponible:
    id: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTA5ZTVlNDQ0MjkxZTY4MzcxNTcwMDJlZTlkNWY2MDRjNjk3MDM5ZWVjN2FjYmEyNDc4ZmIwOTY4NGY5OGZmNyJ9fX0=
    name: "&fRegalo dia &a%day%"
    lore:
      - "&7Estado: &a&lDISPONIBLE"
      - ""
      - "&7¡Click para recibir una recompensa"
      - "&7navideña!"
  regalo_perdido:
    id: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjA2YTNkZTJiMWI5NWY0MmZmZDQ0ODAxOGQxY2MxMWRjNzYzZjlkNWM3MjJjYzFiNmNjM2ZjZmQ0ZjA5MDg5ZSJ9fX0=
    name: "&fRegalo dia &a%day%"
    lore:
      - "&7Estado: &c&lPERDIDO"
      - ""
      - "&7¡No has alcanzado ha recibir esta"
      - "&7recompensa!"
Recompensas:
  1:
    - "eco give %player% 5000"
  2:
    - "eco give %player% 10000"